### PR TITLE
add warning to postinstall

### PR DESCRIPTION
**Pull request by knowbody**
https://github.com/FormidableLabs/victory/issues/98#issuecomment-165595339

### CODE REVIEW

**Comment by coopy** [comment]
@knowbody I needed to add `( ... )` around the `echo && exit 1` condition, otherwise `exit 1` always happens.

The weird `c++` error is a separate issue that has been around for a while (try expanding the `$ npm install` part of the output in https://travis-ci.org/FormidableLabs/victory-axis/jobs/98165885, for example).

**Comment by coopy** [comment]
I created https://github.com/FormidableLabs/victory-axis/issues/71

**Comment by boygirl** [comment]
yay! thanks @coopy

**Comment by ryan-roemer** [comment]
@knowbody @coopy -- Has anyone validated this on Windows? (with the new parens)

**Comment by knowbody** [comment]
@ryan-roemer I didn't, no windows machine. Would be great to add appveyor ASAP

**Comment by ryan-roemer** [comment]
@knowbody -- I see [`ievms`](https://github.com/xdissent/ievms) and [`iectrl`](https://github.com/xdissent/iectrl) in your future ;)

**Comment by knowbody** [comment]
@ryan-roemer the last windows I saw, was win98 :stuck_out_tongue_winking_eye: 

but let me see the "future"

**Comment by ryan-roemer** [comment]
@knowbody -- Here, I did it for you ;)

Here is a "failing" command with parens:

```
> cmd /C "cd lib || (echo hi && exit 1)"
The system cannot find the path specified.
hi

> echo %errorlevel%
1
```

Here is a success command: 

```
> cmd /C "echo ho || (echo hi && exit 1)"
ho

> echo %errorlevel%
0
```

So it appears everything works on windows with the parens as we have it now.

**Comment by knowbody** [comment]
Thank you @ryan-roemer, I'm checking `ievms` and `iectrl` anyway!

**Comment by coopy** [comment]
:+1:

**Pull request merged**
