### PR TITLE
Replicate victory-bar docs change

### PR DESCRIPTION
**Pull request by exogen**
/cc @david-davidson @boygirl

### CODE REVIEW

**Comment by david-davidson** [comment]
@exogen Huh, some weird call stack errors in CI--we can debug this one later.

**Comment by exogen** [comment]
This same error happens when I run on `master`, I think due to the `eslint` version (and related packages). `victory-axis` hasn't done a builder port yet, but it's in a PR.

**Comment by boygirl** [comment]
@exogen I think this pr is safe to merge since we know what's failing CI now.

**Comment by david-davidson** [comment]
@boygirl @exogen Rebased on top of master (w/ `builder` port) => happy CI! Merging. :+1:

**Pull request merged**
